apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-hello
  albels:
    app: argocd-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-hello
   template:
     matadata:
       labels:
         app: argocd-hello
     spec:
       containers:
         - name: go-hello-http
           image: "{{ .Value.image.repository }}:{{ default .Value.image.tag }}"
           ports:
             - containerPort: 80
